project:
  type: website

website:
  title: "AV Dallas County Probation Conditions Databook"
  description: "Breaking the Rules: Rethinking Condition Setting and Enforcement in Juvenile Probation in Dallas County"
  favicon: img/favicon.png
  navbar:
   right:
      - text: "Project and Analysis Plan"
        href: index.html
      - text: "Research/Analysis"
        menu:
          - text: "How are modifications used?"
            href: research_part_1.html
          - text: "Who receives technical violations?"
            href: research_part_2.html
          - text: "When and how often do youth receive technical violations?"
            href: research_part_3.html
          - text: "Why do youth receive technical violations?"
            href: research_part_4.html
          - text: "What happens to youth as the result of a technical violation?"
            href: research_part_5.html
      - text: "Questions and Updates"
        href: jj_av_dallas_questions_updates.html
      - text: "Analytic File Prep"
        href: jj_av_dallas_create_analytic_files.html
      - text: "Sample Descriptives"
        menu:
          - text: "Basic Descriptive Statistics"
            href: jj_av_dallas_preliminary_descriptives.html
          - text: "Codebooks"
            href: jj_av_dallas_data_codebooks.html
          - text: "Data Diagram"
            href: jj_av_dallas_data_diagram_viz.html
      - icon: fab fa-github
        href: https://github.com/CSGJusticeCenter/jj-av-dallas

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-location: left

execute:
  freeze: auto