---
title: "JJ AV Dallas County Data Questions/Updates"
format: html
---

**Data Visualizations**

*1. Overall:* 

a. Universe of kids on probation and risk level distribution over time 

b. Universe of kids and age, under 12, 12, 13, rest 

c. Race distribution and RRI 

d. Length of supervision episode overall and by risk

*2. Modifications:*

a. Modifications and extension rates by year

b. Modification/extension rates by race/ethnicity, gender, age , and risk (or make qualitatively)

c. Modifications prior to technical by year 

*3. Who Receives Technical Violations:*

a. Technical violation rates by year
b. TV rates by gender, race, risk—by episode

*4. When and How do Youth Receive Technical Violations:*

a Overall time and by risk level 

*5. Why do Youth Receive Technical Violations:*

a. Breakdown of reasons over time

b. Make qualitative points for girls, younger, and lower risk 

*6. What happens as a result of TVs:*

a. Youth in community outcomes by years/youth returning from placement

b. Outcomes by risk 

c. Length of extensions by risk/overall 

<br><br>

**Dallas County Data Questions and Responses (June 27, 2023):**

* Re-bucket youngest age categories to align with dept: youthful offenders 10-13 [holdoff on this until we talk to policy team]

* Maybe look into the reasons for modifications prior to a technical violations. Are these modifications the result of a new offense? Discuss with policy team to decide if we should filter out extensions linked to new offense violations?

* Combine unknown and not administered for risk and needs categories

* Add mins and max to sections related to avg number of modification/extensions/technical violations/time to technical violation

* Add row percentages to tables in technical violations descriptives section (section 2) of Who Receives Technical Violations page

* Christian will follow up to confirm that using violation disposition of "DISMISSED OR WITHDRAWN BY DEPARTMENT" can always be interpreted as enrollment in 21-day CAI residential program

* Follow up with Rhonda and Roger about what is included in “general violation” category and average length of supervision extensions.

<br><br>

**Dallas County Data Questions and Responses (June 21, 2023):**

We are curious to explore the proportion of violations filed by a PO that were then rejected by a supervisor. In our last conversation, you noted that all of the technical violation records without a referral number indicate that a PO filed the violation, but that it was rejected by a supervisor. In the violations data, we found that only about 2% of all violations fit this criteria. Does that seem correct to you all?

* Lots of informal rejection is possible – will follow up with wordsmithing assistance. This reflects what is in the data system, but may not speak to the real trend.

* POs will likely only formally file a violation if they feel confident.

* PO has to get permission from supervisor before filing a violation so there should be very few rejected violations 

* ***TO DO: *** Send file of rejected violations to Rhonda Kerl?

<br>

To look into technical violations leading to placement in the 30 day residential program (where if youth are successful, the violation is dismissed), we are using the violation disposition of “DISMISSED OR WITHDRAWN BY DEPARTMENT”. Just double checking, is this the correct violation disposition code to use? Is this disposition code only for youth who are successful in the program? If so, is there is a way to flag youth who are not successful? 

* Yes, this is successful. If youth did not successfully complete, we won’t see violation disposition, but instead should use placement file:

* Placement == emergency shelter (on VOP)

* Placement outcome == violation of court order

* Completed == successful outcome; anything other than completed == not successful outcome

* Also – CAI program is 21 days

* ***TO DO: *** Explore Christian’s strategy for flagging referral to CAI program that would capture both successful and unsuccessful completers. If things look right, use this flag instead and then re-run all pertinent analysis


<br>

Have there been any changes in the use of the 30 day residential program over time? Was it used less in 2020/2021 as a result of COVID? If so, have things changed back in more recent months?

* CAI program (21 day program) – yes, things changed. Youth were served in detention center in more isolated settings (more 1-on-1 meetings, no group meetings). Hill center moved to more isolated programming, as well. Some youth were discharged on a quicker timetable than usual. 2-year period. 

<br>

How should we interpret violations coded as new offenses in the violations file, but coded as VOPs in the offenses file? Were these new offenses that were never formally referred/filed and simply documented as VOPs?

* VOP1 – not enough evidence or judge wants to keep youth on original felony charge (if new offense is just a low-level misdemeanor)

* DA chose to file VOP as opposed to new offense. Example: If a kid is in on a felony but violated on a new offense that is lower level DA may choose to file VOP to keep felony as primary offense. If file new offense the lower offense would override the original felony. Kids have to have felony to be eligible for commitment.

* ***TO DO: *** Look into how often this happens. If often enough, we may not want to analyze new offenses by offense type (b/c we don’t have a representative sample). We’ll potentially need to exclude analysis. 

<br>

We are hoping to calculate the average length of time that a supervision episode is extended as the result of a technical violation. If we just use the supervision extension file that you provided (and don’t join it with the violations file), is it a fairly safe assumption that the vast majority of supervision extensions we see are linked to a violation? Or are there other common non-violation reasons for supervision extensions? 

* Extension can be the result of agreed order, TV, or new offense. 

* Agreed order is usually used to extend for custody or to complete treatment/program or condition. Match extension file to violation file on dates. 

* Join on extension begin date and violation disposition date:

* Within 3-5 days 

* Where violation disposition is modification? Can we use this? Do we have all dispositions for violations? 

* ***TO DO: *** Change business rules to align with this new approach (-1 day or +3 days) and then re-run all pertinent analysis

<br>

We are currently exploring dispositions in the offenses file. Is it safe to assume that the most serious disposition is always linked to the most serious offense (i.e. DOI is “Primary”)? Or could the most serious disposition appear with the record of “Secondary” or “Dismissed” offense? 

* We already have first disposition for the referral – Christian already filtered on this. We don’t have any subsequent tacked on dispositions. 

<br><br>

**Dallas County Data Questions and Responses (April 2023):**

- In the supervision file there appears to be a small number of (around 170) supervision records that have duplicate referral IDs. They seem to have different start dates. How should we interpret these?

* Response from Dallas: Transferring out of jurisdiction is a common reason. Deferred prosecution to failure to comply to pre-adjudication processing is another. Most duplicates should be turned into 1 record. *Internal question:* Should we drop deferred prosecution? VOP isn't possible. 

- Do pure duplicates (every value is duplicated across all columns in files) in violations data file indicate multiple violations? Or should we de-duplicate this file?  

* **Response from Dallas:** Christian will re-send file

- Do missing supervision outcomes and supervision end dates indicate youth was under supervision at time of data pull?  

* **Response from Dallas:** yes

- For “Mental health needs status of the listed juvenile” in “Child” file – does that capture needs status at time of data pull/most recent assessment only? Or does it indicate if youth has ever had documented mental health needs? It appears that the substance use need variable indicates any history that youth have had with substance use services/needs. Is the same true for mental health needs?  

* **Response from Dallas:** both are historic and reflect data at time of data pull 

- How should we interpret missing values for ‘prosecutor_action’, ‘prosecutor_action_date’, ‘disposition_date’, and ‘disposition’ in the violations file? Is there a reason these fields are missing for certain violation records (e.g., could missing disposition information indicate a VOP referral was dropped/withdrawn)?  

* **Response from Dallas:** Are used to access 30-day detention/programming, but not actually sent to prosecution (CIA is voluntary non-secure residential program used as sanction); if kid does well, violation won’t be sent on to prosecutor 

i.	“withdrawn” as disposition means department decision, not prosecutor

ii.	Blank disposition means referral is still pending

iii.	Missing referral number –PO filed violation, but supervisor rejected VOP (no action taken)

iv.	Prosecutor action fields are simply not complete – not sure we can use these fields for anything

v.	Disposition is at referral-level – so most serious offense leads to dispo for entire referral including technicals

*Christian added primary/secondary to indicate if specific offense/violation is leading to the listed dispo*


- What do a supervision phase of “None” and “Warrant” indicate?  

* **Response from Dallas:**

a.	Child has absconded and is on warrant during time period 

b.	None is deferred prosecution 



<br>

**Current Internal Questions & Next Steps:**

-	Does supervision period start with disposition? Or can it include pre-disposition detention? Look at disposition dates and supervision start dates

-	Double check for any overlapping supervision periods by youth throughout file (create flag for this --	I.e. multiple supervision records per youth with different referral IDs)

- How frequently is the violation disposition date the same across multiple violations over time?

-	Calculate time between offense/violation date and disposition date – swift and certain punishment lens

-	Is this violation date or do we need to join back to offense file to get offense date/date of behavior

-	For technical only? Does this need to be a separate violation-level analytic file

-	Create the following counts: 

*	Count of technical violation charges (unique violation records) per disposition (raw count)

*	Count of technical violation charges (unique violation records) per referral (raw count)

*	Count of technical violation referrals (referral IDs where most serious violation is technical) per disposition (raw count)

-	Create flag for prior supervision dispositions (based prior dispositions in offenses file)

-	Calculate length of time to first violation (both technical violation and new offense)

-	Group and de-dup violations file by disposition day and not referral ID (multiple referrals could be consolidated into a single disposition)

*	QUESTION: how we treat violations without dispositions/disposition dates? Should we group by disposition date, if present, and otherwise group by referral? Currently substituting violation file date for violations without disposition date. Need to confirm. From Emily: “Yes, I think we should group by disposition date only if present. So maybe we should keep in mind if we want to count violation type, we can look at offense or grouped by referral. If we want to know outcomes, we are only looking at those disposed.”


<br>

