---
title: "Sample Descriptive Statistics"
format: html
---

In this file, we'll import all of the Dallas County files provided and create preliminary cross-tabulations and merges to explore basic counts, trends, and double check primary keys and joins across the data files. 

See `Codebooks` and `Data Diagram` tabs for more information on each individual data file. 

```{r include=FALSE}
### call libraries
library(easypackages)
libraries("tidyverse","foreign","lubridate","reshape2", "ggplot2","RColorBrewer","knitr","forcats","openxlsx","statar","svDialogs","xlsx", "magrittr","stringr", "data.table","janitor","kableExtra","leaflet", "readr", "rmarkdown","rowr", "gganimate", "gifski","tidycensus","sf","htmltools","acs","tigris","mapview","rgeos", "ggrepel", "censusxy","gdata","lavaan","mclust","tmap", "raster","rgeos","gmapsdistance","viridis","cowplot","lintr","leaflet.extras","censusapi","data.table","gridGraphics","readxl","haven","ggridges","extrafont","extrafontdb","datamodelr","Lahman","DiagrammeR","fs","readxl","rsvg","V8","csgjcr","DataExplorer")
```

```{r include=FALSE,message=FALSE,warning=FALSE}
### set chunk output specifications
knitr::opts_chunk$set(
  echo = TRUE,
  dev = "ragg_png",
  cache = FALSE)

### set theme
theme_set(theme_minimal())
```

```{r include=FALSE}
### pull in dallas data from raw data folder

### set sharepoint path using file.path function (path has different structure than usual so not using csg_sp_path from csgjcr package)
sharepoint_jj_av_dallas_raw_data <- file.path("C:/Users/abyrum/The Council of State Governments/JC Research - JJ_AV - JJ_AV/Dallas/Data/raw")

### using purrr::map, import list of tabs from excel worksheet
dallas_raw_tab_list <- purrr::map(purrr::set_names(excel_sheets(file.path(sharepoint_jj_av_dallas_raw_data,
                                                              "Dallas County (10.1.2017 - 9.30.2022).xlsx"))),
                      read_excel, 
                      path = file.path(sharepoint_jj_av_dallas_raw_data,"Dallas County (10.1.2017 - 9.30.2022).xlsx")) %>% 
  purrr::map(janitor::clean_names)

### clean names of all imported tabs before converting to dataframes
names(dallas_raw_tab_list) <- janitor::make_clean_names(names(dallas_raw_tab_list))

### then convert list of tabs to distinct dataframes with names from tabs
purrr::map(names(dallas_raw_tab_list),
           ~assign(.x, 
                   dallas_raw_tab_list[[.x]], 
        envir = .GlobalEnv)) 
```
